version: "3.9"
services:
  apache-php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/api
    networks:
      - lamp-network
    depends_on:
        - mariadb
        - phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
    networks:
      - lamp-network
    environment:
        PMA_ARBITRARY: 1
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: admin

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - lamp-network
    environment:
      MARIADB_ROOT_PASSWORD: admin

  react-docker:
    container_name: react-docker
    build:
      context: ./react-docker
    ports:
      - "3000:3000"
    # stdin_open: true
    volumes:
      - ./react-docker:/usr/src/app/react-docker
      - /usr/src/app/react-docker/node_modules

volumes:
    mariadb:

networks:
    lamp-network:
      name: lamp-network
